### ISSUE TITLE
TypeLoadException

### ISSUE THREAD

**Issue by JamesVeug** [SpecialAPI/NodeAPI#1]
Hello

I tried making a Node using the example listed in the readme but it gives me this error.
What version of the API did you use to make the mod?

My mod was built using 1.13.0
Game using non-kaycee build

![image](https://user-images.githubusercontent.com/7586886/153703381-0893ab87-2ce7-44db-95d1-0257a1943983.png)

**Comment by SpecialAPI** [comment]
Oh I guess I didn't test it enough for the normal game. Sorry about that. This will get fixed today or tomorrow

**Comment by SpecialAPI** [comment]
Should be fixed now.

**Comment by JamesVeug** [comment]
Yup fixed. thanks!
